- src/components/Chat/Chat.tsx
- src/components/Chat/ModelParams.tsx
- src/components/Chat/ModelSelect.tsx
- src/components/Chat/SystemPrompt.tsx
Preview: <img width="1038" alt="Screenshot 2023-07-03 at 2 55 16 PM" src="https://github.com/KastanDay/ai-ta-frontend/assets/123789373/37d575e3-bf2f-45c3-9a9f-8ed0e70d39dd">
> Dark mode fixes on gpt4 page

- src/components/UIUC-Components/ContextCards.tsx
- src/components/UIUC-Components/EditCourseCard.tsx
- src/components/UIUC-Components/MakeOldCoursePage.tsx
- src/pages/[course_name]/materials.tsx
- src/pages/api/chat.ts
- src/pages/api/contextStuffingHelper.ts
Facing bug with layout, we're getting overflow again :(
> Add urls to ExistingMaterialsPage and context cards

- src/components/UIUC-Components/MakeOldCoursePage.tsx
- src/pages/api/getNomicMapForQueries.ts
- src/pages/api/home/home.tsx
- src/styles/globals.css
- src/types/nomic.ts
WIP, need to finalize the Nomic side. Waiting on Asmita.
> add nomic viz of user questions to /materials

- src/components/UIUC-Components/WebScrape.tsx
* Add nice loading state & auto-refresh for webscrape. We wait until all ingest is complete before refreshing.
> Refine Crawlee UI

- package-lock.json
- package.json
- src/pages/api/documentGroups.ts
- src/utils/dbUtils.ts
- src/utils/qdrantClient.ts
- src/utils/qdrantUtils.ts
need to add environment variables QDRANT_URL, QDRANT_API_KEY, and QDRANT_COLLECTION_NAME
> added functionality for updating qdrant when adding or removing doc_groups

- src/components/UIUC-Components/MakeQueryAnalysisPage.tsx
fixed semantic similarity visualizations link (was previously giving a 404)
> query-analysis-branch-read-more-link-fix

- src/components/Chat/Chat.tsx
- src/components/Chat/ChatInput.tsx
- src/components/Chat/ChatMessage.tsx
- src/pages/api/chat.ts
- src/pages/api/home/home.tsx
- src/types/openai.ts
fixed bug where only one image would be used even if multiple were uploaded; added functionality for using images with new gpt-4 turbo 0409 model
> Fix image upload bug

- src/pages/api/UIUC-api/newsletterUnsubscribe.ts
- src/pages/newsletter-unsubscribe.tsx
The page is here: https://uiuc-chat-git-addunsubscribefromnewsletter-kastandays-projects.vercel.app/newsletter-unsubscribe
This is so we can include a working unsubscribe link in our emails, that's critical for deliverability.
> Add "Unsubscribe from newsletter" page

- src/utils/qdrantUtils.ts
url field is null by default in qdrant - adjusted logic accordingly
> fixed qdrant doc groups functionality for files without url field

- src/components/Chat/Chat.tsx
- src/components/Chat/NewChat.tsx
- src/pages/api/home/home.tsx
- src/pages/cropwizard-licenses.tsx
- src/pages/index.tsx
- src/types/openai.ts
- tsconfig.json
Also refactor OpenAI "preferred model" selection logic into the OpenAI Types.ts file, so it's more centralized. Getting ready for adding more model support.
> Feat (Cropwizard): Add Cropwizard License Disclaimer

- package-lock.json
- package.json
- src/components/UIUC-Components/AuthToEditCourse.tsx
- src/components/UIUC-Components/navbars/GlobalHeader.tsx
- src/middleware.ts
- src/pages/_app.tsx
- src/pages/api/chat-api/keys/generate.ts
- src/pages/sign-in/[[...index]].tsx
- src/utils/modelProviders/anthropic.ts
Migration guide: https://clerk.com/docs/upgrade-guides/core-2/nextjs
The only trick part was they changed how routes are matched on when determining what's public/private. So I had to update some regexes, always dangerous.
> Upgrade to Clerk v5 for <GoogleOneTap /> and better styled components

- src/components/Chat/Chat.tsx
- src/utils/functionCalling/handleFunctionCalling.ts
It was just a missing closing curly brace for `if (tools.length > 0) {`
> Fix the root cause of 'Projects with no tools always fail'

- src/components/UIUC-Components/ApiKeyManagament.tsx
- src/pages/api/chat-api/chat.ts
- src/utils/streamProcessing.ts
Contexts are returned by default on non-streaming API. 
Added flag `retrieval_only`
> Add API flag `retrieval_only` - retrieving ONLY contexts, no LLM invoked

- src/components/UIUC-Components/api-inputs/LLMsApiKeyInputForm.tsx
- src/hooks/useProjectAPIKeys.ts
- src/pages/api/UIUC-api/upsertLLMProviders.ts
It feels lightning fast and high-confidence.
> Debounce the form on /llms. Feel lightning fast 

- next.config.mjs
- package-lock.json
- package.json
- src/components/UIUC-Components/getAllCourseMetaData.ts
- src/pages/_app.tsx
- src/pages/api/UIUC-api/getAllCourseMetadata.ts
- src/pages/api/UIUC-api/getCourseMetadata.ts
- src/pages/api/UIUC-api/getDocsForMaterials.ts
- src/pages/api/home/home.tsx
- src/utils/apiUtils.ts
It was costing $10/1GB of logs to Axiom, we were easily doing 1-2GB per month for no reason.
> Remove Axiom everywhere, too expensive, not useful

- src/app/utils/buildPromptUtils.ts
- src/pages/[course_name]/chat.tsx
- src/pages/[course_name]/prompt.tsx
- src/utils/app/const.ts
implemented functionality for enabling guided learning with url params
> Guided Learning URL Parameters

- src/pages/[course_name]/prompt.tsx
* Nicer UI, especially with the card heading
* Better rest button, proper warning and modal popup confirmation.
> Prompting page UI improvements

- src/components/UIUC-Components/api-inputs/LLMsApiKeyInputForm.tsx
- src/components/UIUC-Components/api-inputs/ModelToggles.tsx
- src/pages/api/UIUC-api/upsertLLMProviders.ts
Root cause: When we migrated from `edge` to `serverless` functions some of the `req.body` parsing didn’t get updated properly.
> Fix LLM Providers on `llms` page - simple body parsing error

- src/app/api/chat/openAI/route.ts
- src/components/Chat/Chat.tsx
- src/pages/[course_name]/chat.tsx
- src/pages/[course_name]/prompt.tsx
- src/pages/api/home/home.tsx
- src/types/chat.ts
- fixed optimize system prompt; added more robust error handling and instructions; no longer falls back on VLADS key
- check document counts prior to document retrieval to avoid flickering loading states of document retrieval on chat page
> Fix optimize system prompt

- src/components/UIUC-Components/APIRequestBuilder.tsx
- src/components/UIUC-Components/APIRequestMaker.tsx
- src/components/UIUC-Components/ApiKeyManagament.tsx
- src/pages/[course_name]/api.tsx
- src/pages/api/chat-api/chat.ts
- src/utils/streamProcessing.ts
> Interactive API request Builder

- src/components/UIUC-Components/navbars/ChatNavbar.tsx
> Add New Chat button to `/chat` page, improve hamburger menu

- src/components/UIUC-Components/navbars/ChatNavbar.tsx
Main fix: Don't show admin dashboard if you're not Owner or Admin. 
* improved break points for non-admins. Made content stay on screen longer (cuz 1 fewer buttons to show).
* Increase horizontal padding to leave room for the sidebar open/close icons
> Hotfix ChatNavbar when user is not admin

- src/components/Chat/Chat.tsx
- src/pages/[course_name]/chat.tsx
- src/pages/chat.tsx
- src/pages/gpt4.tsx
Go to [uiuc.chat/chat](https://uiuc.chat/chat) to have a convo with any of our open source models. Just the base model; no docs or extra spice.
> Add new `uiuc.chat/chat` page that has no documents; usable by all users as a generic chat interface for open source models

- src/app/utils/vllm.ts
- src/components/UIUC-Components/APIRequestBuilder.tsx
- src/pages/[course_name]/api.tsx
- src/pages/_app.tsx
- src/pages/api/chat-api/keys/fetch.ts
- src/utils/apiUtils.ts
- src/utils/modelProviders/OpenAIAzureChat.ts
- src/utils/modelProviders/types/NCSAHostedVLM.ts
> Adding more functionality to request builder

- scripts/update-keycloak-urls.js
- src/components/UIUC-Components/navbars/AuthMenu.tsx
- src/middleware.ts
- src/pages/[course_name]/analysis.tsx
- src/pages/[course_name]/api.tsx
- src/pages/[course_name]/chat.tsx
- src/pages/[course_name]/llms.tsx
The vercel preview URLs for hpc-gpt and illinois-chat were not configured properly due to the script being hardcoded for uiuc-chat-frontend. this PR fixes that. 
The login button has also been fixed to match the styling of the other navbar components.
> HOTFIX Keycloak - proper user email address for convo histories. Fix admin pages auth. 

- src/db/schema.ts
> File upload #316

- src/components/UIUC-Components/navbars/GlobalHeader.tsx
- src/pages/index.tsx
- Remove on hover question mark on top message on main page.
- Add padding to main menu on main page.
> Few more tweaks to front page

- src/pages/index.tsx
Quick PR remove duplicate banner
> duplicate banner
